# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dcfs}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Crichton"]
  s.date = %q{2010-09-02}
  s.default_executable = %q{dcfs}
  s.description = %q{DCFS}
  s.email = ["alex@alexcrichton.com"]
  s.executables = ["dcfs"]
  s.extensions = ["vendor/fusefs/ext/extconf.rb"]
  s.files = [
    "VERSION",
     "lib/dcfs.rb",
     "lib/dcfs/version.rb",
     "vendor/fusefs/API.txt",
     "vendor/fusefs/COPYRIGHT",
     "vendor/fusefs/Changes.txt",
     "vendor/fusefs/Makefile",
     "vendor/fusefs/README.txt",
     "vendor/fusefs/Rakefile",
     "vendor/fusefs/TODO",
     "vendor/fusefs/ext/MANIFEST",
     "vendor/fusefs/ext/Makefile",
     "vendor/fusefs/ext/extconf.rb",
     "vendor/fusefs/ext/fusefs_fuse.c",
     "vendor/fusefs/ext/fusefs_fuse.h",
     "vendor/fusefs/ext/fusefs_fuse.o",
     "vendor/fusefs/ext/fusefs_lib.bundle",
     "vendor/fusefs/ext/fusefs_lib.c",
     "vendor/fusefs/ext/fusefs_lib.o",
     "vendor/fusefs/lib/MANIFEST",
     "vendor/fusefs/lib/fusefs.rb",
     "vendor/fusefs/sample/demo.rb",
     "vendor/fusefs/sample/dictfs.rb",
     "vendor/fusefs/sample/drbfs_client.rb",
     "vendor/fusefs/sample/drbfs_server.rb",
     "vendor/fusefs/sample/hello.rb",
     "vendor/fusefs/sample/mp3stripfs.rb",
     "vendor/fusefs/sample/openurifs.rb",
     "vendor/fusefs/sample/railsfs.rb",
     "vendor/fusefs/sample/sqlfs.rb",
     "vendor/fusefs/sample/yamlfs.rb",
     "vendor/fusefs/sample/yamlfs2.rb",
     "vendor/fusefs/setup.rb"
  ]
  s.homepage = %q{http://github.com/alexcrichton/dcfs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A FUSE filesystem backed by the DC protocol}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

