# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dtellafs}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Crichton"]
  s.date = %q{2010-09-02}
  s.default_executable = %q{dtellafs}
  s.description = %q{Dtella FS}
  s.email = ["alex@alexcrichton.com"]
  s.executables = ["dtellafs"]
  s.files = [
    "VERSION",
     "lib/dtellafs.rb",
     "lib/dtellafs/dir.rb",
     "lib/dtellafs/file.rb",
     "lib/dtellafs/fuse.rb",
     "lib/dtellafs/stat.rb",
     "lib/dtellafs/stat_vfs.rb",
     "lib/dtellafs/version.rb"
  ]
  s.homepage = %q{http://github.com/alexcrichton/dtellafs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A filesystem for Dtella implemented in FUSE}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rfuse-ng>, [">= 0"])
      s.add_runtime_dependency(%q<fargo>, [">= 0"])
      s.add_runtime_dependency(%q<dtellafs>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
    else
      s.add_dependency(%q<rfuse-ng>, [">= 0"])
      s.add_dependency(%q<fargo>, [">= 0"])
      s.add_dependency(%q<dtellafs>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
    end
  else
    s.add_dependency(%q<rfuse-ng>, [">= 0"])
    s.add_dependency(%q<fargo>, [">= 0"])
    s.add_dependency(%q<dtellafs>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
  end
end

