# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dtellafs}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Crichton"]
  s.date = %q{2010-09-02}
  s.default_executable = %q{dtellafs}
  s.description = %q{Dtella FS}
  s.email = ["alex@alexcrichton.com"]
  s.executables = ["dtellafs"]
  s.extensions = ["vendor/rfuse-ng/ext/extconf.rb"]
  s.files = [
    "VERSION",
     "lib/dtellafs.rb",
     "lib/dtellafs/dir.rb",
     "lib/dtellafs/file.rb",
     "lib/dtellafs/fuse.rb",
     "lib/dtellafs/stat.rb",
     "lib/dtellafs/stat_vfs.rb",
     "lib/dtellafs/version.rb",
     "vendor/rfuse-ng/CHANGELOG.txt",
     "vendor/rfuse-ng/LICENSE",
     "vendor/rfuse-ng/README.ng",
     "vendor/rfuse-ng/README.rfuse",
     "vendor/rfuse-ng/Rakefile",
     "vendor/rfuse-ng/THANKS",
     "vendor/rfuse-ng/TODO.txt",
     "vendor/rfuse-ng/ext/Makefile",
     "vendor/rfuse-ng/ext/context.c",
     "vendor/rfuse-ng/ext/context.h",
     "vendor/rfuse-ng/ext/extconf.rb",
     "vendor/rfuse-ng/ext/file_info.c",
     "vendor/rfuse-ng/ext/file_info.h",
     "vendor/rfuse-ng/ext/filler.c",
     "vendor/rfuse-ng/ext/filler.h",
     "vendor/rfuse-ng/ext/gem_make.out",
     "vendor/rfuse-ng/ext/helper.c",
     "vendor/rfuse-ng/ext/helper.h",
     "vendor/rfuse-ng/ext/intern_rfuse.c",
     "vendor/rfuse-ng/ext/intern_rfuse.h",
     "vendor/rfuse-ng/ext/rfuse.c",
     "vendor/rfuse-ng/ext/rfuse.h",
     "vendor/rfuse-ng/ext/rfuse_mod.c",
     "vendor/rfuse-ng/mkmf.log",
     "vendor/rfuse-ng/pkg/rfuse-ng-0.4.0.gem",
     "vendor/rfuse-ng/sample/test-ruby.rb",
     "vendor/rfuse-ng/test/runtest"
  ]
  s.homepage = %q{http://github.com/alexcrichton/dtellafs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A filesystem for Dtella implemented in FUSE}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

